CREATE TABLE IF NOT EXISTS country_codes (
    `Countries_Code` VARCHAR(2) CHARACTER SET utf8,
    `Countries_Name` VARCHAR(38) CHARACTER SET utf8
);
INSERT INTO country_codes VALUES
    ('PR','Puerto Rico'),
    ('PT','Portugal'),
    ('PW','Palau'),
    ('PY','Paraguay'),
    ('QA','Qatar'),
    ('AD','Andorra'),
    ('AE','United Arab Emirates'),
    ('AF','Afghanistan'),
    ('AG','Antigua and Barbuda'),
    ('AI','Anguilla'),
    ('AL','Albania'),
    ('AM','Armenia'),
    ('AO','Angola'),
    ('AQ','Antarctica'),
    ('AR','Argentina'),
    ('AS','American Samoa'),
    ('AT','Austria'),
    ('RE','Reunion'),
    ('AU','Australia'),
    ('AW','Aruba'),
    ('AZ','Azerbaijan'),
    ('RO','Romania'),
    ('BA','Bosnia and Herzegovina'),
    ('BB','Barbados'),
    ('RS','Serbia'),
    ('BD','Bangladesh'),
    ('BE','Belgium'),
    ('RU','Russia'),
    ('BF','Burkina Faso'),
    ('BG','Bulgaria'),
    ('RW','Rwanda'),
    ('BH','Bahrain'),
    ('BI','Burundi'),
    ('BJ','Benin'),
    ('BL','Saint Barthelemy'),
    ('BM','Bermuda'),
    ('BN','Brunei'),
    ('BO','Bolivia'),
    ('SA','Saudi Arabia'),
    ('BQ','Caribbean Netherlands'),
    ('SB','Solomon Islands'),
    ('BR','Brazil'),
    ('SC','Seychelles'),
    ('BS','Bahamas'),
    ('SD','Sudan'),
    ('BT','Bhutan'),
    ('SE','Sweden'),
    ('SG','Singapore'),
    ('BW','Botswana'),
    ('SH','St. Helena'),
    ('SI','Slovenia'),
    ('BY','Belarus'),
    ('BZ','Belize'),
    ('SK','Slovakia'),
    ('SL','Sierra Leone'),
    ('SN','Senegal'),
    ('SO','Somalia'),
    ('CA','Canada'),
    ('SR','Suriname'),
    ('CC','Cocos (Keeling) Islands'),
    ('SS','South Sudan'),
    ('CD','DR Congo'),
    ('ST','Sao Tome and Principe'),
    ('CF','Central African Republic'),
    ('SV','El Salvador'),
    ('CG','Congo'),
    ('CH','Switzerland'),
    ('SX','St Maarten'),
    ('CI','Ivory Coast'),
    ('SY','Syria'),
    ('SZ','Swaziland'),
    ('CK','Cook Islands'),
    ('CL','Chile'),
    ('CM','Cameroon'),
    ('CN','China'),
    ('CO','Colombia'),
    ('CR','Costa Rica'),
    ('TC','Turks and Caicos Islands'),
    ('TD','Chad'),
    ('CU','Cuba'),
    ('CV','Cape Verde'),
    ('TG','Togo'),
    ('CW','Curacao'),
    ('TH','Thailand'),
    ('CX','Christmas Island'),
    ('CY','Cyprus'),
    ('TJ','Tajikistan'),
    ('CZ','Czech Republic'),
    ('TL','East Timor'),
    ('TM','Turkmenistan'),
    ('TN','Tunisia'),
    ('TO','Tonga'),
    ('TR','Turkey'),
    ('TT','Trinidad and Tobago'),
    ('DE','Germany'),
    ('TV','Tuvalu'),
    ('TW','Taiwan'),
    ('DJ','Djibouti'),
    ('TZ','Tanzania'),
    ('DK','Denmark'),
    ('DM','Dominica'),
    ('DO','Dominican Republic'),
    ('UA','Ukraine'),
    ('UG','Uganda'),
    ('DZ','Algeria'),
    ('UK','United Kingdom'),
    ('EC','Ecuador'),
    ('US','United States'),
    ('EE','Estonia'),
    ('EG','Egypt'),
    ('UY','Uruguay'),
    ('UZ','Uzbekistan'),
    ('VA','Vatican City'),
    ('ER','Eritrea'),
    ('VC','Saint Vincent and the Grenadines'),
    ('ES','Spain'),
    ('ET','Ethiopia'),
    ('VE','Venezuela'),
    ('VG','British Virgin Islands'),
    ('VI','US Virgin Islands'),
    ('VN','Vietnam'),
    ('VU','Vanuatu'),
    ('FI','Finland'),
    ('FJ','Fiji'),
    ('FK','Falkland Islands'),
    ('FM','Micronesia'),
    ('FO','Faroe Islands'),
    ('FR','France'),
    ('WF','Wallis and Futuna Islands'),
    ('GA','Gabon'),
    ('WS','Samoa'),
    ('GD','Grenada'),
    ('GE','Georgia'),
    ('GF','French Guiana'),
    ('GG','Guernsey'),
    ('GH','Ghana'),
    ('GI','Gibraltar'),
    ('GL','Greenland'),
    ('GM','Gambia'),
    ('GN','Guinea'),
    ('GP','Guadeloupe'),
    ('GQ','Equatorial Guinea'),
    ('GR','Greece'),
    ('GS','South Georgia & South Sandwich Islands'),
    ('GT','Guatemala'),
    ('GU','Guam'),
    ('GW','Guinea-Bissau'),
    ('GY','Guyana'),
    ('HK','Hong Kong'),
    ('HN','Honduras'),
    ('HR','Croatia'),
    ('HT','Haiti'),
    ('YE','Yemen'),
    ('HU','Hungary'),
    ('ID','Indonesia'),
    ('YT','Mayotte'),
    ('IE','Ireland'),
    ('IL','Israel'),
    ('IN','India'),
    ('ZA','South Africa'),
    ('IQ','Iraq'),
    ('IR','Iran'),
    ('IS','Iceland'),
    ('IT','Italy'),
    ('ZM','Zambia'),
    ('ZW','Zimbabwe'),
    ('JM','Jamaica'),
    ('JO','Jordan'),
    ('JP','Japan'),
    ('KE','Kenya'),
    ('KG','Kyrgyzstan'),
    ('KH','Cambodia'),
    ('KI','Kiribati'),
    ('KM','Comoros'),
    ('KN','Saint Kitts and Nevis'),
    ('KO','Kosovo'),
    ('KP','North Korea'),
    ('KR','South Korea'),
    ('KW','Kuwait'),
    ('KY','Cayman Islands'),
    ('KZ','Kazakhstan'),
    ('LA','Laos'),
    ('LB','Lebanon'),
    ('LC','Saint Lucia'),
    ('LI','Liechtenstein'),
    ('LK','Sri Lanka'),
    ('LR','Liberia'),
    ('LS','Lesotho'),
    ('LT','Lithuania'),
    ('LU','Luxembourg'),
    ('LV','Latvia'),
    ('LY','Libya'),
    ('MA','Morocco'),
    ('MC','Monaco'),
    ('MD','Moldova'),
    ('ME','Montenegro'),
    ('MG','Madagascar'),
    ('MH','Marshall Islands'),
    ('MK','Republic of Macedonia'),
    ('ML','Mali'),
    ('MM','Myanmar'),
    ('MN','Mongolia'),
    ('MO','Macau'),
    ('MP','Northern Mariana Islands'),
    ('MQ','Martinique'),
    ('MR','Mauritania'),
    ('MS','Montserrat'),
    ('MT','Malta'),
    ('MU','Mauritius'),
    ('MV','Maldives'),
    ('MW','Malawi'),
    ('MX','Mexico'),
    ('MY','Malaysia'),
    ('MZ','Mozambique'),
    ('NA','Namibia'),
    ('NC','New Caledonia'),
    ('NE','Niger'),
    ('NG','Nigeria'),
    ('NI','Nicaragua'),
    ('NL','Netherlands'),
    ('NO','Norway'),
    ('NP','Nepal'),
    ('NR','Nauru'),
    ('NU','Niue'),
    ('NZ','New Zealand'),
    ('OM','Oman'),
    ('PA','Panama'),
    ('PE','Peru'),
    ('PF','French Polynesia'),
    ('PG','Papua New Guinea'),
    ('PH','Philippines'),
    ('PK','Pakistan'),
    ('PL','Poland'),
    ('PM','St. Pierre and Miquelon');
